"""Public interfaces for the semantic contract POC."""

from .semantic_ir import (
    Aggregation,
    CanonicalSourceLocation,
    CrossTargetValidationResult,
    Diagnostic,
    DiagnosticSeverity,
    FilterOperator,
    FilterPredicate,
    GenerationResult,
    MetricPattern,
    PATTERN_REGISTRY,
    PatternClassification,
    PowerBIMapping,
    SemanticMetricIR,
    SemanticSignature,
    SnowflakeMapping,
    SupportClassification,
    TargetPlatform,
    canonical_metric_to_ir,
    classify_pattern,
    generate_dax_definition,
    generate_snowflake_definition,
    validate_cross_target,
)

__all__ = [
    "Aggregation",
    "CanonicalSourceLocation",
    "CrossTargetValidationResult",
    "Diagnostic",
    "DiagnosticSeverity",
    "FilterOperator",
    "FilterPredicate",
    "GenerationResult",
    "MetricPattern",
    "PATTERN_REGISTRY",
    "PatternClassification",
    "PowerBIMapping",
    "SemanticMetricIR",
    "SemanticSignature",
    "SnowflakeMapping",
    "SupportClassification",
    "TargetPlatform",
    "canonical_metric_to_ir",
    "classify_pattern",
    "generate_dax_definition",
    "generate_snowflake_definition",
    "validate_cross_target",
]
